"""add autofix patches and org settings

Revision ID: f7b52f9e3bf5
Revises: 1da82d7c93b7
Create Date: 2026-09-16 12:00:21.252668

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f7b52f9e3bf5'
down_revision = '1da82d7c93b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('auto_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('autofix_patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('replacement_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('offered', 'applied', 'rejected', name='patch_status'), nullable=False),
    sa.Column('test_status', sa.Enum('passed', 'failed', 'unverified', name='patch_test_status'), nullable=True),
    sa.Column('review_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('commit_sha', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'file_path', name='uq_patch_run_file')
    )
    op.add_column('review_policies', sa.Column('fix', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_policies', 'fix')
    op.drop_table('autofix_patches')
    op.drop_table('org_settings')
    # ### end Alembic commands ###
